### ISSUE TITLE
 can you create a samle to user  orchard-vue in VueComponents 

### ISSUE THREAD

**Issue by mmdqq** [Lombiq/Orchard-Vue.js#1]
i treid this but it show me shape  VueComponent-App_helloworld not fount.

**Comment by barthamark** [comment]
In a development branch of the https://github.com/Lombiq/Orchard-Training-Demo-Module I've made a tutorial for developing a VueJS application in Orchard Core using this module. 
Beginning from the file linked below you can go through the tutorial by reading the comments and the code and following the "NEXT STATION" comments. Let me know if you made it work.
https://github.com/Lombiq/Orchard-Training-Demo-Module/blob/issue/OCORE-9/Controllers/VueJsController.cs

**Comment by mmdqq** [comment]
![image](https://user-images.githubusercontent.com/4881282/59958191-0c7d6480-94d5-11e9-9839-05c1badd6d62.png)
![image](https://user-images.githubusercontent.com/4881282/59958223-99c0b900-94d5-11e9-8cef-65618bc81748.png)
how to fix this error?

**Comment by mmdqq** [comment]
![image](https://user-images.githubusercontent.com/4881282/59958681-f70c3880-94dc-11e9-856f-3ec28eb9c88c.png)
![image](https://user-images.githubusercontent.com/4881282/59958705-291d9a80-94dd-11e9-842b-493f3ed123f3.png)
I rebuild  Lombiq.TrainingDemo ,it show me error;
but there is no Assets folder in this project

**Comment by barthamark** [comment]
You need to update to the issue/OCORE-9 branch in both Lombiq.TrainingDemo and Lombiq.VueJs modules since they are developed simultaneously.

**Comment by Piedone** [comment]
The Training Demo module's current release contains the new VueJS tutorials as well, starting here: https://github.com/Lombiq/Orchard-Training-Demo-Module/blob/orchard-core/Controllers/VueJsController.cs Take a look at the Readme of the module on how to set it up and use it.
