### ISSUE TITLE
Possibility to use Vuetify JS ?

### ISSUE THREAD

**Issue by kevinvdm88** [Lombiq/Orchard-Vue.js#6]
Hi Lombiq 

Thanks for the sample project to integrate Vue into Orchard Core :) !
Is there also a possibility to use Vuetify (https://vuetifyjs.com/) as well ?

**Comment by barthamark** [comment]
Hi @kevinvdm88 ! Using Vuetify is possible in theory but haven't tried integrating it yet neither Bootstrap Vue. You need to add the node package to your module where the Vue app is initialized in the Gulpfile and do the necessary configuration there and also in your Vue app main.js file. The Vue component shapes (i.e. .cshtml files in the Views/VueComponents folder) can include Vuetify components.
