### ISSUE TITLE
node-sass dependency out of date for node v14

### ISSUE THREAD

**Issue by poroburu** [Lombiq/Orchard-Vue.js#8]
`    "node-sass": "4.12.0",`
The latest node v14 does not support this dependency in package.json. In addition, the download from npm would 404 to a file outside of the the index of downloads in the GitHub release download directory.

Using the latest version 4.14.1 allowed the project to download and build dependencies, and then compile the solution:
`    "node-sass": "4.14.1",`

**Comment by Piedone** [comment]
Looks good, thank you. Fixed.
